### ISSUE TITLE
twitter follow/retweet does not working

### ISSUE THREAD

**Issue by hh8888** [Mubelotix/gleam.io-bot-extension#2]

**Comment by Mubelotix** [comment]
Thanks for your report! The issue is on the gleam.io or Twitter side. Because I can't even use the button manually. But I could implement a workaround. I will wait a few days to see if it is fixed.

**Comment by hh8888** [comment]
Manually, you can do holding shift and click, then enter key when loaded.
But I guess you can not control another window in code?

**Comment by Mubelotix** [comment]
A few weeks ago it was possible to enter without the shift key. The only problem is that the window is never opened. My bot is able to follow Twitter accounts on different windows (that is not difficult). The workarround would be to open the Twitter window directly in my bot, not by clicking on the button. Do you need this quickly?

**Comment by hh8888** [comment]
not urgently, but good to have it working

**Comment by Mubelotix** [comment]
The issue is fixed! I will update the extension on the chrome web store but it can take a few days since Google checks the extension. The last time Google refused the update (for no right reason) so you could have to wait some weeks.
